### ISSUE TITLE
Chinese characters

### ISSUE THREAD

**Issue by jiangyklala** [knuddelsgmbh/jtokkit#19]
Hello, it seems that there is a slight difference in the calculation of Chinese characters between this project and the Tokenizer on the official website.
The model I use is `gpt-3.5-turbo`, and the following are two comparison pictures:
![](https://xiaoj-1309630359.cos.ap-nanjing.myqcloud.com/202304241939148.png)
![](https://xiaoj-1309630359.cos.ap-nanjing.myqcloud.com/202304241941627.png)

**Comment by tox-p** [comment]
Do you mean this tokenizer: https://platform.openai.com/tokenizer ?

The above linked tokenizer uses r50k_base as encoding, while gpt-3.5-turbo uses cl100k_base as encoding.

Try this one, mentioned in [this tiktoken FAQ](https://github.com/openai/tiktoken/issues/98), for your comparison: https://tiktokenizer.vercel.app/ (make sure to use the textbox input and not the message input if comparing the encoding of a raw string like in your screen)

**Comment by jiangyklala** [comment]
Solved ! 
Thanks for answering and  contributing such a good library !
