### ISSUE TITLE
Is there a way to only load the encoding needed?

### ISSUE THREAD

**Issue by blackdiz** [knuddelsgmbh/jtokkit#23]
Hey there, thanks for your hard work. We're interested in using this library on mobile, but we noticed that the initialization process takes some time. We dug into the code and saw that `DefaultEncodingRegistry.initializeDefaultEncodings()` loads all the encodings. We only require the `r50k_base.tiktoken` encoding, so is there a way to load just that one and speed up the initialization?

**Comment by tox-p** [comment]
Currently not, but I would be open to adding such a functionality

Would adding a new `LazyEncodingRegistry` that does not initialize any encodings on construction but does so lazily at first `getEncoding` call for that encoding fit your needs?

**Comment by blackdiz** [comment]
Sure, that would be very appreciated!

**Comment by tox-p** [comment]
I am currently a little bit busy :) Could you open a PR with the change? If I am not mistaken it should be pretty straightforward, just extracting the common functionality of DefaultEncodingRegistry into an AbstractEncodingRegistry, renaming the DefaultEncodingRegistry to EagerEncodingRegistry, creating the LazyEncodingRegistry alongside it and exposing it via a new `newLazyEncodingFactory` in the `Encodings` class

**Comment by blackdiz** [comment]
OK, I don't have the experience to contribute to open-source projects, but I'll give it a try.

**Comment by tox-p** [comment]
Thanks for the implementation :blush: This feature is released as part of 0.5.0 and should soon be available on maven central
