### ISSUE TITLE
Is the Korean token calculation method different from GPT tokenizer?

### ISSUE THREAD

**Issue by DanielDonghaKim** [knuddelsgmbh/jtokkit#27]
```java
EncodingRegistry registry = Encodings.newDefaultEncodingRegistry();
Encoding enc = registry.getEncodingForModel(ModelType.GPT_3_5_TURBO);
List<Integer> encoded = enc.encode("한국어 토큰 수 테스트. JTokkit에서의 한국어 토큰 개수가 달라요.");
```

[GPT Tokenizer](https://platform.openai.com/tokenizer)
I calculated the number of tokens on the page above, but it is printed differently from the number calculated by JTokkit. I want to know why.

![image](https://github.com/knuddelsgmbh/jtokkit/assets/130338058/a6e92a35-078b-4581-bce0-924cc5b9c306)

![image](https://github.com/knuddelsgmbh/jtokkit/assets/130338058/48614fdd-e66c-4b8a-8b75-811c803cbeeb)

**Comment by tox-p** [comment]
Those are different encodings. With JTokkit you used cl100k_base as encoding (the default encoding for gpt-3.5-turbo) but the website you used for reference uses r50k_base.

See this issue, that had a similiar misunderstanding, for more details :slightly_smiling_face: https://github.com/knuddelsgmbh/jtokkit/issues/19
