### ISSUE TITLE
support android

### ISSUE THREAD

**Issue by Trree** [knuddelsgmbh/jtokkit#39]
java.lang.IllegalArgumentException: Unsupported flags: 256

final Pattern regex = Pattern.compile(patternString, Pattern.UNICODE_CHARACTER_CLASS);

**Comment by tox-p** [comment]
You can use version 0.5.0 for now. There is no difference between 0.5.0 and 0.5.1 on Android because Android always uses the unicode character class for regexes.

In the future I may introduce separate builds to tackle this issue, but currently, Android support is not high on my priority list

**Comment by tox-p** [comment]
I added a workaround for now, can you verify that 0.6.1 works again on Android?
