### ISSUE TITLE
Add convenience method to count tokens from a list of `com.theokanning.openai.completion.chat.ChatMessage`

### ISSUE THREAD

**Issue by sualeh** [knuddelsgmbh/jtokkit#46]
The recipe to count tokens in [chatml.md](https://github.com/knuddelsgmbh/jtokkit/blob/12d2b09d7ce45ae53cf8d2af845dcaf2a6d41f0d/docs/docs/getting-started/recipes/chatml.md) does not seem to account for functions. This issue is to request a create a utility or convenience method to count tokens from a list of `com.theokanning.openai.completion.chat.ChatMessage` messages, which takes functions and other types of messages into account.

**Comment by tox-p** [comment]
A utility method is out of scope for this library which only focus is the tokenization algorithm, but I can totally update the docs for the recipe as soon as I find time

For now, I can refer you to the following anwer which did help at least one person with a similar question: https://github.com/knuddelsgmbh/jtokkit/issues/30#issuecomment-1594190763

**Comment by lukaszkorecki** [comment]
Hi! I wrote a Clojure wrapper for jtokkit that does this - you could potentially use it from any JVM language, although it will require working with [Clojure's Java API](https://clojure.github.io/clojure/javadoc/).
