### ISSUE TITLE
jtokkit produce faster YGC

### ISSUE THREAD

**Issue by Taoaozw** [knuddelsgmbh/jtokkit#50]
<img width="1006" alt="截屏2023-08-20 15 12 16" src="https://github.com/knuddelsgmbh/jtokkit/assets/38341571/e9dd1769-3d9e-4359-9d27-f9f323832ff5">

Whether there is room for optimization?

**Comment by tox-p** [comment]
The entries you are highlighting in your screenshot are the cached encoding vocabularies. They will only be loaded once at initialization and never GC'ed, unless you are instantiating a new DefaultEncodingRegistry every operation which is highly discouraged (see the docs for more information)

If you only need a small subset of the 4 encodings (for example, if you only use GPT4), you can use the LazyEncodingRegistry. Again, see the docs for more information
