### ISSUE TITLE
com.knuddels.jtokkit.api.ModelType：Not including chatgpt4 turbo

### ISSUE THREAD

**Issue by gonglb** [knuddelsgmbh/jtokkit#69]
com.knuddels.jtokkit.api.ModelType：Not including chatgpt4 turbo

**Comment by riadhriadh** [comment]
I have submitted a pull request

https://github.com/knuddelsgmbh/jtokkit/pull/74

**Comment by riadhriadh** [comment]
@tox-p

**Comment by tox-p** [comment]
I gave the OpenAI documentation a look and it seems that the GPT 4 Turbo models are not ready yet for production:

> The latest GPT-4 model with improved instruction following, JSON mode, reproducible outputs, parallel function calling, and more. Returns a maximum of 4,096 output tokens. **This preview model is not yet suited for production traffic.**

(emphasis mine)

As stated in #7 I am opposed to including snapshot or preview models to prevent unnecessary library updates when they are superceded. As you may have noticed, I am currently focused elsewhere and want to avoid unnecessary maintenance burden.

As soon as GPT 4 Turbo is production ready, I will gladly update the ModelType enum to include it :slightly_smiling_face: 

Remember, that the ModelType enum is merely a convenience and not a blocker for your use case. You can simply call `EncodingRegistry#getEncoding(EncodingType)` with `EncodingType.CLK100K_BASE` as parameter to get the corresponding encoding.

**Comment by dafriz** [comment]
@tox-p GPT 4 Turbo is production ready. Created PR https://github.com/knuddelsgmbh/jtokkit/pull/94 with the new model name.

**Comment by Plexcalibur** [comment]
Is released with version 1.1.0
