### ISSUE TITLE
Can't work on GraalVM complied Java APP

### ISSUE THREAD

**Issue by kusuri-h** [knuddelsgmbh/jtokkit#89]
My java application is compiled using GraalVM
But I found that in the code I use
```
tempRegistry = Encodings.newDefaultEncodingRegistry();
encodingRegistry.getEncoding(EncodingType.CL100K_BASE);
```
Will cause an error

`java.lang.IllegalStateException: Could not find /com/knuddels/jtokkit/r50k_base.tiktoken in resources`
Is there any solution？

**Comment by tox-p** [comment]
According to https://www.graalvm.org/latest/reference-manual/native-image/guides/include-resources/ you can try adding `-H:IncludeResources=".*tiktoken$"`, although I never tried if it picks up resources in JARs

If all else fails, you can manually extract the files from the jtokkit JAR and add them as mentioned in the linked resource above

**Comment by kusuri-h** [comment]
I added it in the resources-config.json configuration file
such as
```
{"pattern":".*tiktoken$"}
```
then it fixed
Thank you so much!
